//! Golden-file gate for the committed JSON Schema.
//!
//! If this test fails after a struct change, regenerate the file:
//!     cargo run -p xtask -- gen-schema

use std::path::PathBuf;

fn committed_schema_path() -> PathBuf {
    // CARGO_MANIFEST_DIR points at crates/mirror-config; the schema
    // lives at the workspace root under schemas/.
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("schemas")
        .join("mirror-v3.config.schema.json")
}

#[test]
fn committed_schema_matches_current_structs() {
    let path = committed_schema_path();
    let on_disk = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));

    let generated = serde_json::to_string_pretty(&mirror_config::schema()).unwrap() + "\n";

    if on_disk != generated {
        eprintln!(
            "committed schema is stale; regenerate with:\n    cargo run -p xtask -- gen-schema"
        );
        // Show a small diff hint.
        let on_disk_len = on_disk.len();
        let gen_len = generated.len();
        eprintln!("on-disk bytes: {on_disk_len}, generated bytes: {gen_len}");
        panic!("schema mismatch");
    }
}
