//! Golden-file gate for the committed OpenAPI 3.1 document.
//!
//! If this test fails after a handler signature change, regenerate
//! the file:
//!     cargo run -p xtask -- gen-openapi

use std::path::PathBuf;

fn committed_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .unwrap()
        .parent()
        .unwrap()
        .join("schemas")
        .join("mirror-v3.cache.openapi.json")
}

#[test]
fn committed_openapi_matches_current_handlers() {
    let path = committed_path();
    let on_disk = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    let generated = mirror_cache::openapi_json_pretty() + "\n";
    if on_disk != generated {
        eprintln!(
            "committed OpenAPI is stale; regenerate with:\n    cargo run -p xtask -- gen-openapi"
        );
        eprintln!(
            "on-disk bytes: {}, generated bytes: {}",
            on_disk.len(),
            generated.len()
        );
        panic!("openapi mismatch");
    }
}
